// Code generated by protoc-gen-go. DO NOT EDIT.
// source: telegraf.proto

/*
Package remote is a generated protocol buffer package.

It is generated from these files:
	telegraf.proto

It has these top-level messages:
	Greeting
	CurrentState
	CurrentStateResponse
	ConfigPack
	Config
*/
package remote

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type Greeting struct {
	// The identifier of this running instance of remote telegraf
	Tid    string `protobuf:"bytes,1,opt,name=tid" json:"tid,omitempty"`
	Region string `protobuf:"bytes,2,opt,name=region" json:"region,omitempty"`
}

func (m *Greeting) Reset()                    { *m = Greeting{} }
func (m *Greeting) String() string            { return proto.CompactTextString(m) }
func (*Greeting) ProtoMessage()               {}
func (*Greeting) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *Greeting) GetTid() string {
	if m != nil {
		return m.Tid
	}
	return ""
}

func (m *Greeting) GetRegion() string {
	if m != nil {
		return m.Region
	}
	return ""
}

type CurrentState struct {
	// The identifier of this running instance of remote telegraf
	Tid             string   `protobuf:"bytes,1,opt,name=tid" json:"tid,omitempty"`
	Region          string   `protobuf:"bytes,2,opt,name=region" json:"region,omitempty"`
	ActiveConfigIds []string `protobuf:"bytes,3,rep,name=activeConfigIds" json:"activeConfigIds,omitempty"`
}

func (m *CurrentState) Reset()                    { *m = CurrentState{} }
func (m *CurrentState) String() string            { return proto.CompactTextString(m) }
func (*CurrentState) ProtoMessage()               {}
func (*CurrentState) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func (m *CurrentState) GetTid() string {
	if m != nil {
		return m.Tid
	}
	return ""
}

func (m *CurrentState) GetRegion() string {
	if m != nil {
		return m.Region
	}
	return ""
}

func (m *CurrentState) GetActiveConfigIds() []string {
	if m != nil {
		return m.ActiveConfigIds
	}
	return nil
}

type CurrentStateResponse struct {
	RemovedId []string `protobuf:"bytes,1,rep,name=removedId" json:"removedId,omitempty"`
}

func (m *CurrentStateResponse) Reset()                    { *m = CurrentStateResponse{} }
func (m *CurrentStateResponse) String() string            { return proto.CompactTextString(m) }
func (*CurrentStateResponse) ProtoMessage()               {}
func (*CurrentStateResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{2} }

func (m *CurrentStateResponse) GetRemovedId() []string {
	if m != nil {
		return m.RemovedId
	}
	return nil
}

type ConfigPack struct {
	New        []*Config `protobuf:"bytes,1,rep,name=new" json:"new,omitempty"`
	Modified   []*Config `protobuf:"bytes,2,rep,name=modified" json:"modified,omitempty"`
	RemovedIds []string  `protobuf:"bytes,3,rep,name=removedIds" json:"removedIds,omitempty"`
}

func (m *ConfigPack) Reset()                    { *m = ConfigPack{} }
func (m *ConfigPack) String() string            { return proto.CompactTextString(m) }
func (*ConfigPack) ProtoMessage()               {}
func (*ConfigPack) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{3} }

func (m *ConfigPack) GetNew() []*Config {
	if m != nil {
		return m.New
	}
	return nil
}

func (m *ConfigPack) GetModified() []*Config {
	if m != nil {
		return m.Modified
	}
	return nil
}

func (m *ConfigPack) GetRemovedIds() []string {
	if m != nil {
		return m.RemovedIds
	}
	return nil
}

type Config struct {
	Id         string `protobuf:"bytes,1,opt,name=id" json:"id,omitempty"`
	TenantId   string `protobuf:"bytes,2,opt,name=tenantId" json:"tenantId,omitempty"`
	Definition string `protobuf:"bytes,3,opt,name=definition" json:"definition,omitempty"`
}

func (m *Config) Reset()                    { *m = Config{} }
func (m *Config) String() string            { return proto.CompactTextString(m) }
func (*Config) ProtoMessage()               {}
func (*Config) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{4} }

func (m *Config) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *Config) GetTenantId() string {
	if m != nil {
		return m.TenantId
	}
	return ""
}

func (m *Config) GetDefinition() string {
	if m != nil {
		return m.Definition
	}
	return ""
}

func init() {
	proto.RegisterType((*Greeting)(nil), "remote.Greeting")
	proto.RegisterType((*CurrentState)(nil), "remote.CurrentState")
	proto.RegisterType((*CurrentStateResponse)(nil), "remote.CurrentStateResponse")
	proto.RegisterType((*ConfigPack)(nil), "remote.ConfigPack")
	proto.RegisterType((*Config)(nil), "remote.Config")
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// Client API for TelegrafRemote service

type TelegrafRemoteClient interface {
	StartConfigStreaming(ctx context.Context, in *Greeting, opts ...grpc.CallOption) (TelegrafRemote_StartConfigStreamingClient, error)
	ReportState(ctx context.Context, in *CurrentState, opts ...grpc.CallOption) (*CurrentStateResponse, error)
}

type telegrafRemoteClient struct {
	cc *grpc.ClientConn
}

func NewTelegrafRemoteClient(cc *grpc.ClientConn) TelegrafRemoteClient {
	return &telegrafRemoteClient{cc}
}

func (c *telegrafRemoteClient) StartConfigStreaming(ctx context.Context, in *Greeting, opts ...grpc.CallOption) (TelegrafRemote_StartConfigStreamingClient, error) {
	stream, err := grpc.NewClientStream(ctx, &_TelegrafRemote_serviceDesc.Streams[0], c.cc, "/remote.TelegrafRemote/StartConfigStreaming", opts...)
	if err != nil {
		return nil, err
	}
	x := &telegrafRemoteStartConfigStreamingClient{stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type TelegrafRemote_StartConfigStreamingClient interface {
	Recv() (*ConfigPack, error)
	grpc.ClientStream
}

type telegrafRemoteStartConfigStreamingClient struct {
	grpc.ClientStream
}

func (x *telegrafRemoteStartConfigStreamingClient) Recv() (*ConfigPack, error) {
	m := new(ConfigPack)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func (c *telegrafRemoteClient) ReportState(ctx context.Context, in *CurrentState, opts ...grpc.CallOption) (*CurrentStateResponse, error) {
	out := new(CurrentStateResponse)
	err := grpc.Invoke(ctx, "/remote.TelegrafRemote/ReportState", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for TelegrafRemote service

type TelegrafRemoteServer interface {
	StartConfigStreaming(*Greeting, TelegrafRemote_StartConfigStreamingServer) error
	ReportState(context.Context, *CurrentState) (*CurrentStateResponse, error)
}

func RegisterTelegrafRemoteServer(s *grpc.Server, srv TelegrafRemoteServer) {
	s.RegisterService(&_TelegrafRemote_serviceDesc, srv)
}

func _TelegrafRemote_StartConfigStreaming_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(Greeting)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(TelegrafRemoteServer).StartConfigStreaming(m, &telegrafRemoteStartConfigStreamingServer{stream})
}

type TelegrafRemote_StartConfigStreamingServer interface {
	Send(*ConfigPack) error
	grpc.ServerStream
}

type telegrafRemoteStartConfigStreamingServer struct {
	grpc.ServerStream
}

func (x *telegrafRemoteStartConfigStreamingServer) Send(m *ConfigPack) error {
	return x.ServerStream.SendMsg(m)
}

func _TelegrafRemote_ReportState_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CurrentState)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TelegrafRemoteServer).ReportState(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/remote.TelegrafRemote/ReportState",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TelegrafRemoteServer).ReportState(ctx, req.(*CurrentState))
	}
	return interceptor(ctx, in, info, handler)
}

var _TelegrafRemote_serviceDesc = grpc.ServiceDesc{
	ServiceName: "remote.TelegrafRemote",
	HandlerType: (*TelegrafRemoteServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "ReportState",
			Handler:    _TelegrafRemote_ReportState_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "StartConfigStreaming",
			Handler:       _TelegrafRemote_StartConfigStreaming_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "telegraf.proto",
}

func init() { proto.RegisterFile("telegraf.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 326 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x8c, 0x52, 0x4d, 0x6b, 0xc2, 0x40,
	0x10, 0x35, 0x09, 0x04, 0x1d, 0x4b, 0x5a, 0x06, 0x29, 0x41, 0xa4, 0xc8, 0x9e, 0xa4, 0x07, 0x29,
	0xd6, 0x1f, 0x50, 0xf0, 0x50, 0xbc, 0x95, 0xe8, 0x1f, 0x58, 0xdd, 0x49, 0x58, 0x5a, 0x77, 0x65,
	0x9d, 0x5a, 0xe8, 0x1f, 0xe9, 0xdf, 0x2d, 0x9b, 0xaf, 0xa6, 0xc5, 0x43, 0x6f, 0xd9, 0x37, 0x6f,
	0xf6, 0xbd, 0x7d, 0x2f, 0x90, 0x30, 0xbd, 0x51, 0xe1, 0x64, 0x3e, 0x3f, 0x3a, 0xcb, 0x16, 0x63,
	0x47, 0x07, 0xcb, 0x24, 0x96, 0xd0, 0x7f, 0x76, 0x44, 0xac, 0x4d, 0x81, 0x37, 0x10, 0xb1, 0x56,
	0x69, 0x30, 0x0d, 0x66, 0x83, 0xcc, 0x7f, 0xe2, 0x2d, 0xc4, 0x8e, 0x0a, 0x6d, 0x4d, 0x1a, 0x96,
	0x60, 0x7d, 0x12, 0x3b, 0xb8, 0x5a, 0xbd, 0x3b, 0x47, 0x86, 0x37, 0x2c, 0x99, 0xfe, 0xbf, 0x89,
	0x33, 0xb8, 0x96, 0x7b, 0xd6, 0x67, 0x5a, 0x59, 0x93, 0xeb, 0x62, 0xad, 0x4e, 0x69, 0x34, 0x8d,
	0x66, 0x83, 0xec, 0x2f, 0x2c, 0x96, 0x30, 0xea, 0x6a, 0x64, 0x74, 0x3a, 0x5a, 0x73, 0x22, 0x9c,
	0xc0, 0xc0, 0x7b, 0x3f, 0x93, 0x5a, 0x7b, 0x45, 0xbf, 0xfb, 0x03, 0x88, 0x4f, 0x80, 0xea, 0x8a,
	0x17, 0xb9, 0x7f, 0xc5, 0x29, 0x44, 0x86, 0x3e, 0x4a, 0xd6, 0x70, 0x91, 0xcc, 0xab, 0x37, 0xcf,
	0x2b, 0x42, 0xe6, 0x47, 0x78, 0x0f, 0xfd, 0x83, 0x55, 0x3a, 0xd7, 0xa4, 0xd2, 0xf0, 0x22, 0xad,
	0x9d, 0xe3, 0x1d, 0x40, 0x2b, 0xd4, 0xd8, 0xee, 0x20, 0x62, 0x0b, 0x71, 0xb5, 0x83, 0x09, 0x84,
	0x6d, 0x1c, 0xa1, 0x56, 0x38, 0x86, 0x3e, 0x93, 0x91, 0x86, 0xd7, 0xaa, 0xce, 0xa3, 0x3d, 0xfb,
	0x5b, 0x15, 0xe5, 0xda, 0x68, 0xf6, 0x69, 0x45, 0xe5, 0xb4, 0x83, 0x2c, 0xbe, 0x02, 0x48, 0xb6,
	0x75, 0x79, 0x59, 0xe9, 0x0c, 0x9f, 0x60, 0xb4, 0x61, 0xe9, 0xb8, 0x52, 0xdb, 0xb0, 0x23, 0x79,
	0x28, 0x0b, 0x6c, 0xac, 0x37, 0x95, 0x8e, 0xf1, 0xf7, 0x63, 0x7c, 0x28, 0xa2, 0xf7, 0x10, 0xe0,
	0x0a, 0x86, 0x19, 0x1d, 0xad, 0xab, 0xfb, 0x1b, 0xb5, 0xb4, 0x4e, 0xe2, 0xe3, 0xc9, 0x25, 0xb4,
	0xe9, 0x41, 0xf4, 0x76, 0x71, 0xf9, 0x2b, 0x3d, 0x7e, 0x07, 0x00, 0x00, 0xff, 0xff, 0x62, 0x76,
	0xd8, 0xbd, 0x5c, 0x02, 0x00, 0x00,
}
