// Code generated by protoc-gen-go. DO NOT EDIT.
// source: telegraf.proto

/*
Package remote is a generated protocol buffer package.

It is generated from these files:
	telegraf.proto

It has these top-level messages:
	Identifiers
	Greeting
	CurrentState
	CurrentStateResponse
	ConfigPack
	Config
*/
package remote

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type Identifiers struct {
	// The identifier of this running instance of remote telegraf
	Tid string `protobuf:"bytes,1,opt,name=tid" json:"tid,omitempty"`
	// Optionally indicates that this is a telegraf that operates in a region on behalf of multi-tenants
	Region string `protobuf:"bytes,2,opt,name=region" json:"region,omitempty"`
	// Optionally indicates that this is a telegraf situated on a specific tenant's node
	Tenant string `protobuf:"bytes,3,opt,name=tenant" json:"tenant,omitempty"`
}

func (m *Identifiers) Reset()                    { *m = Identifiers{} }
func (m *Identifiers) String() string            { return proto.CompactTextString(m) }
func (*Identifiers) ProtoMessage()               {}
func (*Identifiers) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *Identifiers) GetTid() string {
	if m != nil {
		return m.Tid
	}
	return ""
}

func (m *Identifiers) GetRegion() string {
	if m != nil {
		return m.Region
	}
	return ""
}

func (m *Identifiers) GetTenant() string {
	if m != nil {
		return m.Tenant
	}
	return ""
}

type Greeting struct {
	Identifiers *Identifiers      `protobuf:"bytes,1,opt,name=identifiers" json:"identifiers,omitempty"`
	NodeTag     map[string]string `protobuf:"bytes,2,rep,name=nodeTag" json:"nodeTag,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
}

func (m *Greeting) Reset()                    { *m = Greeting{} }
func (m *Greeting) String() string            { return proto.CompactTextString(m) }
func (*Greeting) ProtoMessage()               {}
func (*Greeting) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func (m *Greeting) GetIdentifiers() *Identifiers {
	if m != nil {
		return m.Identifiers
	}
	return nil
}

func (m *Greeting) GetNodeTag() map[string]string {
	if m != nil {
		return m.NodeTag
	}
	return nil
}

type CurrentState struct {
	Identifiers     *Identifiers `protobuf:"bytes,1,opt,name=identifiers" json:"identifiers,omitempty"`
	ActiveConfigIds []string     `protobuf:"bytes,2,rep,name=activeConfigIds" json:"activeConfigIds,omitempty"`
}

func (m *CurrentState) Reset()                    { *m = CurrentState{} }
func (m *CurrentState) String() string            { return proto.CompactTextString(m) }
func (*CurrentState) ProtoMessage()               {}
func (*CurrentState) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{2} }

func (m *CurrentState) GetIdentifiers() *Identifiers {
	if m != nil {
		return m.Identifiers
	}
	return nil
}

func (m *CurrentState) GetActiveConfigIds() []string {
	if m != nil {
		return m.ActiveConfigIds
	}
	return nil
}

type CurrentStateResponse struct {
	RemovedId []string `protobuf:"bytes,1,rep,name=removedId" json:"removedId,omitempty"`
}

func (m *CurrentStateResponse) Reset()                    { *m = CurrentStateResponse{} }
func (m *CurrentStateResponse) String() string            { return proto.CompactTextString(m) }
func (*CurrentStateResponse) ProtoMessage()               {}
func (*CurrentStateResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{3} }

func (m *CurrentStateResponse) GetRemovedId() []string {
	if m != nil {
		return m.RemovedId
	}
	return nil
}

type ConfigPack struct {
	New        []*Config `protobuf:"bytes,1,rep,name=new" json:"new,omitempty"`
	Modified   []*Config `protobuf:"bytes,2,rep,name=modified" json:"modified,omitempty"`
	RemovedIds []string  `protobuf:"bytes,3,rep,name=removedIds" json:"removedIds,omitempty"`
}

func (m *ConfigPack) Reset()                    { *m = ConfigPack{} }
func (m *ConfigPack) String() string            { return proto.CompactTextString(m) }
func (*ConfigPack) ProtoMessage()               {}
func (*ConfigPack) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{4} }

func (m *ConfigPack) GetNew() []*Config {
	if m != nil {
		return m.New
	}
	return nil
}

func (m *ConfigPack) GetModified() []*Config {
	if m != nil {
		return m.Modified
	}
	return nil
}

func (m *ConfigPack) GetRemovedIds() []string {
	if m != nil {
		return m.RemovedIds
	}
	return nil
}

type Config struct {
	Id         string `protobuf:"bytes,1,opt,name=id" json:"id,omitempty"`
	TenantId   string `protobuf:"bytes,2,opt,name=tenantId" json:"tenantId,omitempty"`
	Definition string `protobuf:"bytes,3,opt,name=definition" json:"definition,omitempty"`
	Title      string `protobuf:"bytes,4,opt,name=title" json:"title,omitempty"`
}

func (m *Config) Reset()                    { *m = Config{} }
func (m *Config) String() string            { return proto.CompactTextString(m) }
func (*Config) ProtoMessage()               {}
func (*Config) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{5} }

func (m *Config) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *Config) GetTenantId() string {
	if m != nil {
		return m.TenantId
	}
	return ""
}

func (m *Config) GetDefinition() string {
	if m != nil {
		return m.Definition
	}
	return ""
}

func (m *Config) GetTitle() string {
	if m != nil {
		return m.Title
	}
	return ""
}

func init() {
	proto.RegisterType((*Identifiers)(nil), "remote.Identifiers")
	proto.RegisterType((*Greeting)(nil), "remote.Greeting")
	proto.RegisterType((*CurrentState)(nil), "remote.CurrentState")
	proto.RegisterType((*CurrentStateResponse)(nil), "remote.CurrentStateResponse")
	proto.RegisterType((*ConfigPack)(nil), "remote.ConfigPack")
	proto.RegisterType((*Config)(nil), "remote.Config")
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// Client API for TelegrafRemote service

type TelegrafRemoteClient interface {
	StartConfigStreaming(ctx context.Context, in *Greeting, opts ...grpc.CallOption) (TelegrafRemote_StartConfigStreamingClient, error)
	ReportState(ctx context.Context, in *CurrentState, opts ...grpc.CallOption) (*CurrentStateResponse, error)
}

type telegrafRemoteClient struct {
	cc *grpc.ClientConn
}

func NewTelegrafRemoteClient(cc *grpc.ClientConn) TelegrafRemoteClient {
	return &telegrafRemoteClient{cc}
}

func (c *telegrafRemoteClient) StartConfigStreaming(ctx context.Context, in *Greeting, opts ...grpc.CallOption) (TelegrafRemote_StartConfigStreamingClient, error) {
	stream, err := grpc.NewClientStream(ctx, &_TelegrafRemote_serviceDesc.Streams[0], c.cc, "/remote.TelegrafRemote/StartConfigStreaming", opts...)
	if err != nil {
		return nil, err
	}
	x := &telegrafRemoteStartConfigStreamingClient{stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type TelegrafRemote_StartConfigStreamingClient interface {
	Recv() (*ConfigPack, error)
	grpc.ClientStream
}

type telegrafRemoteStartConfigStreamingClient struct {
	grpc.ClientStream
}

func (x *telegrafRemoteStartConfigStreamingClient) Recv() (*ConfigPack, error) {
	m := new(ConfigPack)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func (c *telegrafRemoteClient) ReportState(ctx context.Context, in *CurrentState, opts ...grpc.CallOption) (*CurrentStateResponse, error) {
	out := new(CurrentStateResponse)
	err := grpc.Invoke(ctx, "/remote.TelegrafRemote/ReportState", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for TelegrafRemote service

type TelegrafRemoteServer interface {
	StartConfigStreaming(*Greeting, TelegrafRemote_StartConfigStreamingServer) error
	ReportState(context.Context, *CurrentState) (*CurrentStateResponse, error)
}

func RegisterTelegrafRemoteServer(s *grpc.Server, srv TelegrafRemoteServer) {
	s.RegisterService(&_TelegrafRemote_serviceDesc, srv)
}

func _TelegrafRemote_StartConfigStreaming_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(Greeting)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(TelegrafRemoteServer).StartConfigStreaming(m, &telegrafRemoteStartConfigStreamingServer{stream})
}

type TelegrafRemote_StartConfigStreamingServer interface {
	Send(*ConfigPack) error
	grpc.ServerStream
}

type telegrafRemoteStartConfigStreamingServer struct {
	grpc.ServerStream
}

func (x *telegrafRemoteStartConfigStreamingServer) Send(m *ConfigPack) error {
	return x.ServerStream.SendMsg(m)
}

func _TelegrafRemote_ReportState_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CurrentState)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TelegrafRemoteServer).ReportState(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/remote.TelegrafRemote/ReportState",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TelegrafRemoteServer).ReportState(ctx, req.(*CurrentState))
	}
	return interceptor(ctx, in, info, handler)
}

var _TelegrafRemote_serviceDesc = grpc.ServiceDesc{
	ServiceName: "remote.TelegrafRemote",
	HandlerType: (*TelegrafRemoteServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "ReportState",
			Handler:    _TelegrafRemote_ReportState_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "StartConfigStreaming",
			Handler:       _TelegrafRemote_StartConfigStreaming_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "telegraf.proto",
}

func init() { proto.RegisterFile("telegraf.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 437 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x9c, 0x53, 0xc1, 0x8e, 0xd3, 0x30,
	0x10, 0xdd, 0x24, 0x50, 0xda, 0xc9, 0xaa, 0xac, 0x4c, 0x85, 0xa2, 0x6a, 0x41, 0x95, 0x4f, 0x15,
	0x87, 0x0a, 0x15, 0x10, 0x68, 0x4f, 0x48, 0x15, 0x42, 0xbd, 0x00, 0x72, 0xf7, 0x07, 0xcc, 0x7a,
	0x1a, 0x99, 0xb6, 0x76, 0xe5, 0xcc, 0x16, 0x95, 0x1f, 0xe1, 0x4f, 0xf8, 0x3e, 0x64, 0x3b, 0x49,
	0x43, 0xc5, 0x69, 0x6f, 0x99, 0x37, 0xe3, 0x79, 0x33, 0xf3, 0x5e, 0x60, 0x48, 0xb8, 0xc5, 0xd2,
	0xc9, 0xf5, 0x6c, 0xef, 0x2c, 0x59, 0xd6, 0x73, 0xb8, 0xb3, 0x84, 0xfc, 0x2b, 0xe4, 0x4b, 0x85,
	0x86, 0xf4, 0x5a, 0xa3, 0xab, 0xd8, 0x15, 0x64, 0xa4, 0x55, 0x91, 0x4c, 0x92, 0xe9, 0x40, 0xf8,
	0x4f, 0xf6, 0x1c, 0x7a, 0x0e, 0x4b, 0x6d, 0x4d, 0x91, 0x06, 0xb0, 0x8e, 0x3c, 0x4e, 0x68, 0xa4,
	0xa1, 0x22, 0x8b, 0x78, 0x8c, 0xf8, 0x9f, 0x04, 0xfa, 0x9f, 0x1d, 0x22, 0x69, 0x53, 0xb2, 0x77,
	0x90, 0xeb, 0x53, 0xf7, 0xd0, 0x36, 0x9f, 0x3f, 0x9b, 0x45, 0xee, 0x59, 0x87, 0x58, 0x74, 0xeb,
	0xd8, 0x7b, 0x78, 0x62, 0xac, 0xc2, 0x5b, 0x59, 0x16, 0xe9, 0x24, 0x9b, 0xe6, 0xf3, 0x17, 0xcd,
	0x93, 0xa6, 0xf3, 0xec, 0x4b, 0xcc, 0x7f, 0x32, 0xe4, 0x8e, 0xa2, 0xa9, 0x1e, 0xdf, 0xc0, 0x65,
	0x37, 0xe1, 0xd7, 0xd9, 0xe0, 0xb1, 0x59, 0x67, 0x83, 0x47, 0x36, 0x82, 0xc7, 0x07, 0xb9, 0xbd,
	0xc7, 0x7a, 0x9b, 0x18, 0xdc, 0xa4, 0x1f, 0x12, 0x6e, 0xe1, 0x72, 0x71, 0xef, 0x1c, 0x1a, 0x5a,
	0x91, 0x24, 0x7c, 0xe8, 0xec, 0x53, 0x78, 0x2a, 0xef, 0x48, 0x1f, 0x70, 0x61, 0xcd, 0x5a, 0x97,
	0x4b, 0x55, 0x85, 0x1d, 0x06, 0xe2, 0x1c, 0xe6, 0x6f, 0x61, 0xd4, 0x25, 0x14, 0x58, 0xed, 0xad,
	0xa9, 0x90, 0x5d, 0xc3, 0xc0, 0x93, 0x1c, 0x50, 0x2d, 0xbd, 0x12, 0xfe, 0xed, 0x09, 0xe0, 0xbf,
	0x00, 0x62, 0x8b, 0x6f, 0xf2, 0x6e, 0xc3, 0x26, 0x90, 0x19, 0xfc, 0x19, 0xaa, 0xf2, 0xf9, 0xb0,
	0x19, 0x2e, 0x16, 0x08, 0x9f, 0x62, 0xaf, 0xa0, 0xbf, 0xb3, 0xca, 0x0f, 0xa7, 0xea, 0x63, 0x9e,
	0x97, 0xb5, 0x79, 0xf6, 0x12, 0xa0, 0x25, 0xaa, 0x8a, 0x2c, 0x50, 0x77, 0x10, 0xfe, 0x03, 0x7a,
	0xf1, 0x0d, 0x1b, 0x42, 0xda, 0xda, 0x24, 0xd5, 0x8a, 0x8d, 0xa1, 0x1f, 0xf5, 0x5f, 0xaa, 0xfa,
	0xb2, 0x6d, 0xec, 0xbb, 0x2a, 0x5c, 0x6b, 0xa3, 0xc9, 0xbb, 0x28, 0xba, 0xa5, 0x83, 0x78, 0x49,
	0x48, 0xd3, 0x16, 0x8b, 0x47, 0x51, 0x92, 0x10, 0xcc, 0x7f, 0x27, 0x30, 0xbc, 0xad, 0x3d, 0x2b,
	0xc2, 0xbc, 0xec, 0x23, 0x8c, 0x56, 0x24, 0x1d, 0xc5, 0x19, 0x56, 0xe4, 0x50, 0xee, 0xbc, 0xcb,
	0xae, 0xce, 0xdd, 0x31, 0x66, 0xff, 0xae, 0xe8, 0x4f, 0xc5, 0x2f, 0x5e, 0x27, 0x6c, 0x01, 0xb9,
	0xc0, 0xbd, 0x75, 0xb5, 0xc4, 0xa3, 0xb6, 0xac, 0xa3, 0xc3, 0xf8, 0xfa, 0x7f, 0x68, 0xa3, 0x0e,
	0xbf, 0xf8, 0xde, 0x0b, 0x7f, 0xd0, 0x9b, 0xbf, 0x01, 0x00, 0x00, 0xff, 0xff, 0x42, 0xb8, 0x7b,
	0xb0, 0x53, 0x03, 0x00, 0x00,
}
